---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: jonathanidica/windows2012r2
    transport:
      name: winrm
      elevated: true

suites:
  - name: dc
    run_list:
      - recipe[sharepoint::ad_install]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
